osx_image: xcode9.3 # Xcode Version
language: objective-c # iOS Objective-C
before_install:
    - gem install xcpretty # xcodebuild appearance tool
before_script:
    - set -o pipefail # For Debug Log
script:
    - xcodebuild test -project ./Aisatsu/Aisatsu.xcodeproj -scheme AisatsuTest -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.3,name=iPhone8' | xcpretty -c # xcodebuild build and test
